# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba399b70cf88f46039bec47363ff59e8e1d892507f8335fd2485742f26d02bd26edcf798a1eb4b1f680c59de710b154af05dcb1a33358200fac268ae14d8eeac

test:
  secret_key_base: f507a40340d6d4b886eacff934966161310d1e7f114e4d68731ac9755486835c9f27436a2141874af32113706705f9b2427d1b3044f273c1c07516dd3099763b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
